version: '3.9'

services:
  redis:
    image: redislabs/redistimeseries:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

#  redis_insight:
#    image: redislabs/redisinsight:latest
#    container_name: redisinsight
#    ports:
#      - "5540:5540"
#    environment:
#      - REDIS_URL=redis://redis:6379
#    depends_on:
#      - redis

  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A cronjob worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  celery_beat:
    build:
      context: .
    container_name: celery_beat
    command: celery -A cronjob beat --loglevel=error
    depends_on:
      - redis
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # Persistent local storage for Prometheus data
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  prometheus_collector:
    build:
      context: .
    container_name: prometheus_collector
    command: python3 prometheus_collector.py
    ports:
      - "5000:5000"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  redis_data:
  grafana_data:
  prometheus_data:
