version: '3.9'

services:
  redis:
    image: redislabs/redistimeseries:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A cronjob worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  celery_beat:
    build:
      context: .
    container_name: celery_beat
    command: celery -A cronjob beat --loglevel=error
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis_data:
